ROADMAP_DATA = [
    {
        "stage_number": 1,
        "title": "Входной фундамент",
        "description": "Знакомство с форматом ЕГЭ и базовыми понятиями",
        "tasks": [1, 4, 7, 11],
        "checkpoint": False,
        "estimated_hours": 8,
    },
    {
        "stage_number": 2,
        "title": "Базовые задания",
        "description": "Логика, базы данных, электронные таблицы, кодирование",
        "tasks": [2, 3, 9, 10],
        "checkpoint": True,
        "checkpoint_name": "Контрольная: базовый блок",
        "estimated_hours": 12,
    },
    {
        "stage_number": 3,
        "title": "Ранний кодовый блок",
        "description": "Первые задания, решаемые через Python",
        "tasks": [5, 6, 8, 14],
        "checkpoint": True,
        "checkpoint_name": "Контрольная: кодовый блок I",
        "estimated_hours": 16,
    },
    {
        "stage_number": 4,
        "title": "Средний кодовый блок",
        "description": "Алгоритмы, рекурсия, системы счисления",
        "tasks": [12, 13, 15, 16, 17],
        "checkpoint": True,
        "checkpoint_name": "Контрольная: кодовый блок II",
        "estimated_hours": 20,
    },
    {
        "stage_number": 5,
        "title": "Продвинутый блок",
        "description": "Теория игр, обработка данных, строки",
        "tasks": [18, 19, 20, 21, 22, 23, 24],
        "checkpoint": True,
        "checkpoint_name": "Контрольная: продвинутый блок",
        "estimated_hours": 24,
    },
    {
        "stage_number": 6,
        "title": "Финальная доводка",
        "description": "Сложные задания: файлы, оптимизация, комплексные задачи",
        "tasks": [25, 26, 27],
        "checkpoint": True,
        "checkpoint_name": "Финальная контрольная",
        "estimated_hours": 20,
    },
    {
        "stage_number": 7,
        "title": "Пробники и стабилизация",
        "description": "Полные пробные экзамены, закрепление слабых мест",
        "tasks": [],
        "checkpoint": False,
        "is_mock_stage": True,
        "estimated_hours": 16,
    },
]
